parameters:
#    ad_mon_premier.example.class: AD\MonPremierBundle\Example

services:
#    ad_mon_premier.example:
#        class: %ad_mon_premier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
